export const LOAD_EVENTS_REQUEST = "LOAD_EVENTS_REQUEST";
export const LOAD_EVENTS_SUCCESS = "LOAD_EVENTS_SUCCESS";
export const LOAD_EVENTS_FAILURE = "LOAD_EVENTS_FAILURE";

export const TOGGLE_SELECTION = "TOGGLE_SELECTION";
export const REMOVE_SELECTION = "REMOVE_SELECTION";